In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.tsv','\t')

C:\Users\DRITI SINGHANIA\AppData\Local\Temp\ipykernel_29952\776792249.py:1: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.tsv','\t')


In [3]:
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [4]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [5]:
df.isna().mean()

Age                         0.0
Attrition                   0.0
BusinessTravel              0.0
DailyRate                   0.0
Department                  0.0
DistanceFromHome            0.0
Education                   0.0
EducationField              0.0
EmployeeCount               0.0
EmployeeNumber              0.0
EnvironmentSatisfaction     0.0
Gender                      0.0
HourlyRate                  0.0
JobInvolvement              0.0
JobLevel                    0.0
JobRole                     0.0
JobSatisfaction             0.0
MaritalStatus               0.0
MonthlyIncome               0.0
MonthlyRate                 0.0
NumCompaniesWorked          0.0
Over18                      0.0
OverTime                    0.0
PercentSalaryHike           0.0
PerformanceRating           0.0
RelationshipSatisfaction    0.0
StandardHours               0.0
StockOptionLevel            0.0
TotalWorkingYears           0.0
TrainingTimesLastYear       0.0
WorkLifeBalance             0.0
YearsAtC

In [6]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
df['Attrition'] = label_encoder.fit_transform(df['Attrition'])

In [7]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np
encoder = OrdinalEncoder(categories=[['Non-Travel','Travel_Rarely', 'Travel_Frequently']])
df['BusinessTravel'] = encoder.fit_transform(df[['BusinessTravel']])
df['BusinessTravel'].unique()

array([1., 2., 0.])

In [8]:
df.head()

Age  Attrition  BusinessTravel  DailyRate              Department  \
0   41          1             1.0       1102                   Sales   
1   49          0             2.0        279  Research & Development   
2   37          1             1.0       1373  Research & Development   
3   33          0             2.0       1392  Research & Development   
4   27          0             1.0        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Attrition']),df['Attrition'],test_size=0.2,random_state=42)

In [10]:
df['BusinessTravel'].unique()

array([1., 2., 0.])

In [11]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [12]:
df['Department'].unique()

array(['Sales', 'Research & Development', 'Human Resources'], dtype=object)

In [13]:
df['EducationField'].unique()

array(['Life Sciences', 'Other', 'Medical', 'Marketing',
       'Technical Degree', 'Human Resources'], dtype=object)

In [14]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [15]:
df['JobRole'].unique()

array(['Sales Executive', 'Research Scientist', 'Laboratory Technician',
       'Manufacturing Director', 'Healthcare Representative', 'Manager',
       'Sales Representative', 'Research Director', 'Human Resources'],
      dtype=object)

In [16]:
df['MaritalStatus'].unique()

array(['Single', 'Married', 'Divorced'], dtype=object)

In [17]:
df['Over18'].unique()
df = df.drop(columns=['Over18'],axis=1)

In [18]:
df['OverTime'].unique()

array(['Yes', 'No'], dtype=object)

In [19]:
df.head()

Age  Attrition  BusinessTravel  DailyRate              Department  \
0   41          1             1.0       1102                   Sales   
1   49          0             2.0        279  Research & Development   
2   37          1             1.0       1373  Research & Development   
3   33          0             2.0       1392  Research & Development   
4   27          0             1.0        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 34 columns]

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Attrition']),df['Attrition'],test_size=0.2,random_state=42)

In [21]:
categorical = ['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']

In [22]:
from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
trf1 = ColumnTransformer([
    ('ohe',OneHotEncoder(handle_unknown='ignore'),categorical)    
], remainder ='passthrough')

In [23]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
rf = RandomForestClassifier(oob_score=True)

In [24]:
from sklearn.pipeline import Pipeline
pipe = Pipeline([
    ('trf1',trf1),
    ('rf',rf)
])

In [25]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['BusinessTravel',
                                                   'Department',
                                                   'EducationField', 'Gender',
                                                   'JobRole', 'MaritalStatus',
                                                   'OverTime'])])),
                ('rf', RandomForestClassifier(oob_score=True))])

In [26]:
rf.oob_score_

0.8545918367346939

In [27]:
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.8673469387755102

In [28]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy')

array([0.85169492, 0.88510638, 0.85531915, 0.84255319, 0.85957447])

In [29]:
param_grid = {
    "rf__n_estimators": [20,60,100,120],
    "rf__max_features":[0.2,0.6,1.0],
    "rf__max_depth":[2,8,None],
    "rf__max_samples":[0.5,0.75,1.0]
}

In [30]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, param_grid, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

C:\Users\DRITI SINGHANIA\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:615: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\DRITI SINGHANIA\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:615: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\DRITI SINGHANIA\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:615: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\DRITI SINGHANIA\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:615: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\DRITI SINGHANIA\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:615: UserWarnin

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trf1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['BusinessTravel',
                                                                          'Department',
                                                                          'EducationField',
                                                                          'Gender',
                                                                          'JobRole',
                                                                          'MaritalStatus',
                                                                          'OverTime'])])),
                                       ('rf',
                                        RandomForestClassifier(oob_score=True))]),
             param_grid={'rf__max_depth': [2, 8, None],
                         'rf__max_features': [0.2, 0.6, 1.0],
                         'rf__max_samples': [0.5, 0.75, 1.0],
                         'rf__n_estimators': [20, 60, 100, 120]},
             scoring='accuracy')

In [31]:
grid.best_score_

0.8656473133790119

In [32]:
grid.best_params_

{'rf__max_depth': None,
 'rf__max_features': 0.2,
 'rf__max_samples': 1.0,
 'rf__n_estimators': 120}

In [33]:
a = rf.feature_importances_

In [34]:
a

array([0.00333625, 0.0074741 , 0.01268131, 0.00230651, 0.00911859,
       0.00895388, 0.00322232, 0.0067111 , 0.00539319, 0.00790102,
       0.00297626, 0.00600633, 0.00570472, 0.00735535, 0.00192291,
       0.00272473, 0.00773624, 0.00108526, 0.00230773, 0.00080506,
       0.00476178, 0.00785916, 0.00732031, 0.00531673, 0.00740694,
       0.0209645 , 0.03501667, 0.04236678, 0.05395783, 0.04378474,
       0.04244418, 0.01687157, 0.        , 0.04234619, 0.02388281,
       0.04112442, 0.01957567, 0.02375774, 0.02276267, 0.07484074,
       0.04690292, 0.03224665, 0.02608261, 0.00420806, 0.01771115,
       0.        , 0.02686394, 0.04500075, 0.0232132 , 0.02006571,
       0.03877431, 0.02458149, 0.0232951 , 0.02896981])

In [35]:
sorted_index_array = np.argsort(a) 

sorted_array = a[sorted_index_array] 
  
print("Sorted array:", sorted_array) 

n = 7

rslt = sorted_array[-7 : ] 

Sorted array: [0.         0.         0.00080506 0.00108526 0.00192291 0.00230651
 0.00230773 0.00272473 0.00297626 0.00322232 0.00333625 0.00420806
 0.00476178 0.00531673 0.00539319 0.00570472 0.00600633 0.0067111
 0.00732031 0.00735535 0.00740694 0.0074741  0.00773624 0.00785916
 0.00790102 0.00895388 0.00911859 0.01268131 0.01687157 0.01771115
 0.01957567 0.02006571 0.0209645  0.02276267 0.0232132  0.0232951
 0.02375774 0.02388281 0.02458149 0.02608261 0.02686394 0.02896981
 0.03224665 0.03501667 0.03877431 0.04112442 0.04234619 0.04236678
 0.04244418 0.04378474 0.04500075 0.04690292 0.05395783 0.07484074]


In [36]:
print(rslt)

[0.04236678 0.04244418 0.04378474 0.04500075 0.04690292 0.05395783
 0.07484074]


In [37]:
max_7_features = np.argsort(a)[-7:]

# Get the maximum 5 values
max_7_values = a[max_7_features]

In [38]:
print("Top 7 maximum feature importances:")
for feature_index in max_7_features:
    print(f"Feature's Index after encoding in the dataset: {feature_index}, Importance: {a[feature_index]}")

Top 7 maximum feature importances:
Feature's Index after encoding in the dataset: 27, Importance: 0.04236678255015341
Feature's Index after encoding in the dataset: 30, Importance: 0.042444176701546224
Feature's Index after encoding in the dataset: 29, Importance: 0.04378473694163646
Feature's Index after encoding in the dataset: 47, Importance: 0.04500075469916028
Feature's Index after encoding in the dataset: 40, Importance: 0.04690292336631249
Feature's Index after encoding in the dataset: 28, Importance: 0.053957834033257566
Feature's Index after encoding in the dataset: 39, Importance: 0.07484074024893657


In [39]:
import pickle
pickle.dump(pipe,open('rf.pkl','wb'))

In [40]:
import pickle
import numpy as np

In [41]:
lr_pipe = pickle.load(open('rf.pkl','rb'))

In [42]:
test_data = pd.DataFrame({
    'Age': [24],
    'BusinessTravel': ['Travel_Rarely'],
    'DailyRate': [350],
    'Department': ['Research & Development'],
    'DistanceFromHome': [21],
    'Education': [2],
    'EducationField': ['Technical Degree'],
    'EmployeeCount': [1],
    'EmployeeNumber': [1551],
    'EnvironmentSatisfaction': [3],
    'Gender': ['Male'],
    'HourlyRate': [57],
    'JobInvolvement': [2],
    'JobLevel': [1],
    'JobRole': ['Laboratory Technician'],
    'JobSatisfaction': [1],
    'MaritalStatus': ['Divorced'],
    'MonthlyIncome': [2296],
    'MonthlyRate': [10036],
    'NumCompaniesWorked': [0],
    'OverTime': ['No'],
    'PercentSalaryHike': [14],
    'PerformanceRating': [3],
    'RelationshipSatisfaction': [2],
    'StandardHours': [80],
    'StockOptionLevel': [3],
    'TotalWorkingYears': [2],
    'TrainingTimesLastYear': [3],
    'WorkLifeBalance': [3],
    'YearsAtCompany': [1],
    'YearsInCurrentRole': [1],
    'YearsSinceLastPromotion': [0],
    'YearsWithCurrManager': [0]
})

In [43]:
lr_pipe.predict(test_data)

array([0])

In [44]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Attrition']),df['Attrition'], test_size=0.3, random_state=42)

In [45]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [46]:
from sklearn.pipeline import Pipeline
pipe1 = Pipeline([
    ('trf1',trf1),
    ('model',model)
])

In [47]:
pipe1.fit(X_train,y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['BusinessTravel',
                                                   'Department',
                                                   'EducationField', 'Gender',
                                                   'JobRole', 'MaritalStatus',
                                                   'OverTime'])])),
                ('model', GaussianNB())])

In [48]:
y_pred = pipe1.predict(X_test)

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7278911564625851

In [50]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)
# Hence recall is a better metrics

0.3939393939393939

In [51]:
from sklearn.metrics import recall_score
recall_score(y_test,y_pred)

0.639344262295082

In [52]:
import pickle
pickle.dump(pipe,open('nb.pkl','wb'))

In [53]:
import pickle
import numpy as np

In [54]:
nb_pipe = pickle.load(open('rf.pkl','rb'))

In [55]:
test_data = pd.DataFrame({
    'Age': [24],
    'BusinessTravel': ['Travel_Rarely'],
    'DailyRate': [350],
    'Department': ['Research & Development'],
    'DistanceFromHome': [21],
    'Education': [2],
    'EducationField': ['Technical Degree'],
    'EmployeeCount': [1],
    'EmployeeNumber': [1551],
    'EnvironmentSatisfaction': [3],
    'Gender': ['Male'],
    'HourlyRate': [57],
    'JobInvolvement': [2],
    'JobLevel': [1],
    'JobRole': ['Laboratory Technician'],
    'JobSatisfaction': [1],
    'MaritalStatus': ['Divorced'],
    'MonthlyIncome': [2296],
    'MonthlyRate': [10036],
    'NumCompaniesWorked': [0],
    'OverTime': ['No'],
    'PercentSalaryHike': [14],
    'PerformanceRating': [3],
    'RelationshipSatisfaction': [2],
    'StandardHours': [80],
    'StockOptionLevel': [3],
    'TotalWorkingYears': [2],
    'TrainingTimesLastYear': [3],
    'WorkLifeBalance': [3],
    'YearsAtCompany': [1],
    'YearsInCurrentRole': [1],
    'YearsSinceLastPromotion': [0],
    'YearsWithCurrManager': [0]
})

In [56]:
nb_pipe.predict(test_data)

array([0])

In [57]:
y_train

714     0
135     0
1271    1
477     0
806     0
       ..
1130    0
1294    0
860     1
1459    0
1126    0
Name: Attrition, Length: 1029, dtype: int32

In [58]:
y_scores = model.predict_proba(X_test)[:,1]

C:\Users\DRITI SINGHANIA\anaconda3\lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(


ValueError: could not convert string to float: 'Sales'

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)